### ISSUE TITLE
Solve with SimpleNewtonRaphson fails with ComplexF64

### ISSUE THREAD

**Issue by davidschlegel** [SciML/SimpleNonlinearSolve.jl#10]
When defining for example a DAE through `DifferentialEquations.jl`, some initialization algorithms go through `SimpleNewtonRaphson`.  If the elementary type is complex, say ComplexF64, then the line
```
atol = abstol !== nothing ? abstol : oneunit(eltype(T)) * (eps(one(eltype(T))))^(4 // 5)
```
in the function `SciMLBase.solve(prob::NonlinearProblem, alg::SimpleNewtonRaphson,...)` gives a complex atol, resulting in an error
`ERROR: TypeError: in keyword argument atol, expected Real, got a value of type ComplexF64`
I suggest to take the absolute value of `oneunit`, so
```
atol = abstol !== nothing ? abstol : abs(oneunit(eltype(T))) * (eps(one(eltype(T))))^(4 // 5)
```
I don't know if this is type stable though...

**Comment by ChrisRackauckas** [comment]
That is type stable. Seems like a fine thing to change.
