### ISSUE TITLE
Return codes for trust region failures 

### ISSUE THREAD

**Issue by FHoltorf** [SciML/SimpleNonlinearSolve.jl#101]
Hey, 

For the trust region implementation we currently return `ReturnCode.Success` even when the algorithm stalled: 

https://github.com/SciML/SimpleNonlinearSolve.jl/blob/a65354ab2617f6f9e7bbf9c30c712e7c8a1c97fc/src/trustRegion.jl#L164-L166

and

https://github.com/SciML/SimpleNonlinearSolve.jl/blob/a65354ab2617f6f9e7bbf9c30c712e7c8a1c97fc/src/trustRegion.jl#L156-L158

Changing that to `ReturnCode.ConvergenceFailure` leads to several broken tests and I don't quite understand what is happening there. Who should I talk to?

**Comment by ChrisRackauckas** [comment]
@avik-pal

**Comment by avik-pal** [comment]
Yeah, I am working on cleaning the code, I can take care of that. There was this exact same problem in the old NonlinearSolve as well, which has now been fixed.

**Comment by ChrisRackauckas** [comment]
Was this handled?

**Comment by avik-pal** [comment]
yes this is fixed

**Comment by avik-pal** [comment]
@ChrisRackauckas this can be closed
