### ISSUE TITLE
Implementing Broyden solver

### ISSUE THREAD

**Issue by CCsimon123** [SciML/SimpleNonlinearSolve.jl#13]
This will be my first open-source PR, so I've got a couple of questions.

1. Is it ok to add a dependency on "LinearAlgebra"? (added "using LinearAlgebra")
2. I'm not 100% sure what supertype to use. I'm using "AbstractSimpleNonlinearSolveAlgorithm" at the moment.

**Comment by ChrisRackauckas** [comment]
Yes and yes.

**Comment by ChrisRackauckas** [comment]
Completed via https://github.com/SciML/SimpleNonlinearSolve.jl/pull/14
