### ISSUE TITLE
confusingly worded warning when tspan doesn't include root

### ISSUE THREAD

**Issue by ajwheeler** [SciML/SimpleNonlinearSolve.jl#161]
The warning introduced in #158 is great, however the first time I got it I had to do some googling to figure out what it meant.  Specifically the wording made me think that opposite signs were required for `tspan[1]` and `tspan[2]`.  I suggest tweaking it to say that tspan doesn't include a root, or similar.  

I can open a PR if you approve of this change.

**Comment by ChrisRackauckas** [comment]
Yeah, open a PR. It's easiest to understand whether the new wording is better by seeing the suggestion.
