### ISSUE TITLE
Improve singularity handling in Klement's method

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SimpleNonlinearSolve.jl#19]
See comments in https://github.com/SciML/SimpleNonlinearSolve.jl/pull/18

**Comment by ChrisRackauckas** [comment]
#22 left some loose ends here, see https://github.com/SciML/SimpleNonlinearSolve.jl/pull/22#discussion_r1061868490

**Comment by ChrisRackauckas** [comment]
@avik-pal you're handling this in the NonlinearSolve PR?

**Comment by avik-pal** [comment]
I saw this. The nonlinear solve PR already has a singularity check implemented via `cond`. Is there a way to improve that?

**Comment by avik-pal** [comment]
@ChrisRackauckas could we add a function like `issingular` to LinearSolve which can fallback to `cond` while for certain factorizations we can do a cheaper check?

**Comment by ChrisRackauckas** [comment]
https://docs.sciml.ai/ArrayInterface/stable/linearalgebra/#Generic-Matrix-Functions

**Comment by avik-pal** [comment]
These don't have calls that directly use the factorizations, right?

**Comment by ChrisRackauckas** [comment]
For a dense matrix it needs to fallback https://github.com/JuliaArrays/ArrayInterface.jl/blob/e5bd756e180754b61d2f41892b7744cb6393633d/src/ArrayInterface.jl#L370, but in many cases it will do something smart.

**Comment by avik-pal** [comment]
https://github.com/SciML/NonlinearSolve.jl/pull/257 fixes this
