### ISSUE TITLE
Depreciation warning about retcodes

### ISSUE THREAD

**Issue by thomvet** [SciML/SimpleNonlinearSolve.jl#21]
```
f(x) = x^2
u0 = 1
probN = NonlinearProblem(f, u0, p)
solver = solve(probN, NewtonRaphson())
```

Results in the warning:
```
 Warning: Backwards compatability support of the new return codes to Symbols will be deprecated with the Julia v1.9 release. Please see https://docs.sciml.ai/SciMLBase/stable/interfaces/Solutions/#retcodes for more information
└ @ SciMLBase C:\Users\thvt\.julia\packages\SciMLBase\nzvrv\src\retcodes.jl:360
```

(this is on NonlinearSolve v1.1.1)

Meaning that somewhere old style retcodes are still used in this? I haven't dug down where yet.

**Comment by ChrisRackauckas** [comment]
I'm not sure what you're talking about. First of all, the code you shared errors because `f` doesn't have the right arguments and `p` is undefined. But secondly, the fixed version:

```julia
using NonlinearSolve
f(x,p) = x^2
u0 = 1
probN = NonlinearProblem(f, u0)
solver = solve(probN, NewtonRaphson())
```

Doesn't throw a warning? So I'm closing this as I don't see a workable MWE here, but if you have one that does warn please share.

**Comment by thomvet** [comment]
Sorry, typically issue of coming up with an MWE in an old julia session. The MWE still give me the warning, but after moving over to a clean environment with just NonlinearSolve in it, it's gone. Must have been something in my previous environment.

So, sorry for the noise!

**Comment by ChrisRackauckas** [comment]
No worries, always better to have an old report than no reports at all.
