### ISSUE TITLE
explanation for the need for this repo compared to full nonlinearsolve in readme?

### ISSUE THREAD

**Issue by anandijain** [SciML/SimpleNonlinearSolve.jl#4]
is this like simplediffeq where it's just for teaching? or is it getting used in DiffEq

**Comment by ChrisRackauckas** [comment]
It doesn't have a DiffEqBase dependency. And it can be made more lean by using StaticArraysCore.

It's used in DiffEqBase. SimpleNonlinearSolve -> DiffEqBase -> NonlinearSolve. Otherwise there's a circular dependency.

It's useful for the small linear solves that don't need all of the fancy stuff.

**Comment by ChrisRackauckas** [comment]
added
