### ISSUE TITLE
Improve the performance of LBroyden

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/SimpleNonlinearSolve.jl#42]
https://github.com/SciML/SimpleNonlinearSolve.jl/pull/41

https://github.com/SciML/SimpleNonlinearSolve.jl/blob/main/src/lbroyden.jl#L47-L49
https://github.com/SciML/SimpleNonlinearSolve.jl/blob/main/src/lbroyden.jl#L61-L62
https://github.com/SciML/SimpleNonlinearSolve.jl/blob/main/src/lbroyden.jl#L64-L66
https://github.com/SciML/SimpleNonlinearSolve.jl/blob/main/src/lbroyden.jl#L71

These all allocate. We can instead allocate once and make those all in-place. There's no need for a NonlinearSolve.jl version because it's still a rather straightforward method (no Jacobians), and this is really the only tweak that needs to be done.

**Comment by avik-pal** [comment]
If someone needs a reference to a non-allocating version https://github.com/SciML/DeepEquilibriumNetworks.jl/blob/998c8b64ec9920a49cd59f2d98a43b308e26f632/src/solvers/discrete/limited_memory_broyden.jl (the code there is a bit clunky)

**Comment by ChrisRackauckas** [comment]
this is being handled?

**Comment by avik-pal** [comment]
Let's keep the implementation here as it is. I will pull the improvements into NonlinearSolve.jl

**Comment by avik-pal** [comment]
https://github.com/SciML/NonlinearSolve.jl/pull/257 fixes this
