### ISSUE TITLE
Mention related packages in the README.md/docs

### ISSUE THREAD

**Issue by ranocha** [SciML/SimpleNonlinearSolve.jl#44]
It would be nice to mention other, related packages, e.g.,
- https://github.com/JuliaMath/Roots.jl
- https://github.com/SciML/NonlinearSolve.jl for a high-level interface
- https://github.com/CliMA/RootSolvers.jl
- https://github.com/CliMA/NonlinearSolvers.jl

**Comment by ChrisRackauckas** [comment]
Updated to point to NonlinearSolve in the README, which points everywhere it can through the wrapper. To add more, we should just wrap them and add them to the docs.
