### ISSUE TITLE
The `Tutorials` link leads to an `access denied` page.

### ISSUE THREAD

**Issue by lockywolf** [SciML/SimpleNonlinearSolve.jl#90]
Dear SciML developers, the link in the `README.md` (https://docs.sciml.ai/NonlinearSolve/stable/tutorials/nonlinear/#Using-Bracketing-Methods) leads to an `Access Denied` page.

```
I tried with several IP addresses, both v4 and v6.

**Comment by ChrisRackauckas** [comment]
The link is https://docs.sciml.ai/NonlinearSolve/stable/solvers/BracketingSolvers/ or https://docs.sciml.ai/NonlinearSolve/stable/tutorials/getting_started/#Problem-Type-2:-Solving-Interval-Rootfinding-Problems-with-Bracketing-Methods. Where did you find that link?

**Comment by ChrisRackauckas** [comment]
Since the correct links work I'm closing, but please if you have more information on where you got that link I'd like to know.

**Comment by lockywolf** [comment]
If you open the page `https://github.com/SciML/SimpleNonlinearSolve.jl` and click on "Tutorials", it will redirect you to the broken page.

It is line 41 of the README.md, `[Tutorials](https://docs.sciml.ai/NonlinearSolve/stable/tutorials/nonlinear/#Using-Bracketing-Methods)`.
