### ISSUE TITLE
Warning: NLSolveTerminationCondition has been deprecated in favor of the new dispatch based termination conditions.

### ISSUE THREAD

**Issue by prbzrg** [SciML/SimpleNonlinearSolve.jl#92]
```julia
┌ SimpleNonlinearSolve [727e6d20-b764-4bd8-a329-72de5adea6c7]
│  ┌ Warning: NLSolveTerminationCondition has been deprecated in favor of the new dispatch based termination conditions. Please use the new termination conditions API!
│  │   caller = SimpleNonlinearSolve.Broyden() at broyden.jl:20
│  └ @ SimpleNonlinearSolve ~/.julia/packages/SimpleNonlinearSolve/cW4pm/src/broyden.jl:20
│  ┌ Warning: NLSolveTerminationCondition has been deprecated in favor of the new dispatch based termination conditions. Please use the new termination conditions API!
│  │   caller = SimpleNonlinearSolve.SimpleDFSane() at dfsane.jl:67
│  └ @ SimpleNonlinearSolve ~/.julia/packages/SimpleNonlinearSolve/cW4pm/src/dfsane.jl:67
└  
```

https://github.com/SciML/NonlinearSolve.jl/actions/runs/6716303943/job/18252333439#step:6:744

**Comment by ChrisRackauckas** [comment]
I think @avik-pal is handling all of these?

**Comment by avik-pal** [comment]
The easiest way is to do a breaking change of SimpleNonlinearSolve for this (and that would mean another breaking change for NonlinearSolve).

(But it is quite low on my priority list)

**Comment by ChrisRackauckas** [comment]
> (But it is quite low on my priority list)

Are you sure? 😅 😅 😅 😅 😅 😅 😅

**Comment by avik-pal** [comment]
It works... Also I don't want a breaking release for NonlinearSolve rn

**Comment by ChrisRackauckas** [comment]
We shouldn't default in ways that are throwing warnings though.

**Comment by avik-pal** [comment]
Only on CI because depwarn is on

**Comment by bpfel** [comment]
Is it possible that 0.1.24 is a breaking change?

We have a few packages relying on `DifferentialEquations` and now I cannot precompile julia unless I pin `SimpleNonlinearSolve` to 0.1.23.

Not sure if this is the right place to post this, but the change, as this issue were very recent.

**Comment by ChrisRackauckas** [comment]
It's not a breaking change. It just required v1.9 because of changes in SciMLBase that required v1.9, so it was yanked and the new v0.1.25 fixes the lower bound.

**Comment by ChrisRackauckas** [comment]
Deprecations completed by the v1.0
