### ISSUE TITLE
Precompile failure?

### ISSUE THREAD

**Issue by cmhyett** [SciML/SimpleNonlinearSolve.jl#96]
Running a test, `SimpleNonlinearSolve` fails to precompile, throwing error `LoadError: UndefVarError: `NonlinearLeastSquaresProblem` not defined` breaking downstream precompilation.

Stacktrace can be found here https://github.com/SciML/MethodOfLines.jl/actions/runs/6711389565/job/18403689020?pr=285

**Comment by ChrisRackauckas** [comment]
Some lower bound bumps were missed. Fixed by https://github.com/JuliaRegistries/General/pull/94886
